# change the followings to match your Github username and repo name
baseurl: "/augcle" # the name of your github repo
url: "https://augcle.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "August C."
description: En hjemmeside om August Clemmensen

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: August Clemmensen
author-bio: Direktør for BAGSTIV  # change to false to hide
author-image: 0166.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
